# Form implementation generated from reading ui file 'Port_Selector.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Port_selec")
        Dialog.resize(442, 132)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Port_list = QtWidgets.QComboBox(Dialog)
        self.Port_list.setGeometry(QtCore.QRect(20, 30, 251, 26))
        self.Port_list.setObjectName("Port_list")
        self.Bandrate_list = QtWidgets.QComboBox(Dialog)
        self.Bandrate_list.setGeometry(QtCore.QRect(270, 30, 111, 26))
        self.Bandrate_list.setObjectName("Bandrate_list")
        self.reload_button = QtWidgets.QPushButton(Dialog)
        self.reload_button.setGeometry(QtCore.QRect(390, 20, 41, 41))
        self.reload_button.setObjectName("reload_button")

        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(quit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.reload_button.setText(_translate("Dialog", "🔄"))
